kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: simpletest
  name: pod-reader
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["list","get"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]